const PIPELINE_STEPS = [
  {
    title: "Derive age",
    detail: "Age is calculated from birth year for the year being simulated.",
  },
  {
    title: "Births",
    detail: "Eligible parent cohorts and period rules create new residents.",
  },
  {
    title: "Deaths",
    detail: "Mortality rules remove residents, with age weighting where configured.",
  },
  {
    title: "External migration",
    detail: "Immigration adds residents and emigration removes residents.",
  },
  {
    title: "Internal relocation",
    detail: "Residents move between the eleven present-day LGD areas.",
  },
  {
    title: "Community transition",
    detail: "Estimated changes in reported community background are applied.",
  },
];

export function AboutPage() {
  return (
    <main className="about-page">
      <article className="about-content">
        <div className="about-hero">
          <div>
            <div className="brand-kicker">ABOUT THIS PROJECT</div>
            <h1>A toy for exploring assumptions</h1>
            <p className="about-lede">
              This project asks what might happen when a small set of demographic
              assumptions is allowed to play out over time. It is an experiment,
              not a forecast.
            </p>
          </div>
          <span className="about-status">Experimental toy</span>
        </div>

        <blockquote className="model-quote">
          <p>“All models are wrong, but some are useful.”</p>
          <cite>
            George E. P. Box, {" "}
            <a
              href="https://doi.org/10.1016/B978-0-12-438150-6.50018-2"
              target="_blank"
              rel="noreferrer"
            >
              Robustness in the Strategy of Scientific Model Building
            </a>
            {" "}(1979)
          </cite>
        </blockquote>

        <section className="about-warning" aria-labelledby="not-a-forecast">
          <div className="about-warning-mark" aria-hidden="true">!</div>
          <div>
            <h2 id="not-a-forecast">Not a serious demographic model</h2>
            <p>
              This is deliberately a toy. It does not claim to be a professional,
              academic or official demographic model. Anyone with expertise in
              demography, statistics, polling, Northern Ireland or social science
              should expect to find many problems, omissions and debatable
              assumptions. Its limited purpose is to examine some basic assumptions
              and make their broad consequences visible.
            </p>
          </div>
        </section>

        <div className="about-card-grid">
          <section className="about-card" aria-labelledby="ai-generated">
            <div className="about-card-number" aria-hidden="true">01</div>
            <h2 id="ai-generated">AI-generated code</h2>
            <p>
              All code in this repository was generated by AI under human
              direction. It has not received strong independent, expert or
              line-by-line verification. Bugs are likely. Treat the interface,
              calculations and outputs with caution.
            </p>
          </section>
          <section className="about-card" aria-labelledby="not-evidence">
            <div className="about-card-number" aria-hidden="true">02</div>
            <h2 id="not-evidence">Sources do not equal validation</h2>
            <p>
              Some starting totals and controls are based on Census, NISRA and
              polling material, while unavailable relationships are explicit
              estimates. Citing real data does not prove that its transformation,
              combination or projection here is sound.
            </p>
          </section>
          <section className="about-card" aria-labelledby="not-a-prediction">
            <div className="about-card-number" aria-hidden="true">03</div>
            <h2 id="not-a-prediction">Scenarios, not predictions</h2>
            <p>
              A run shows the consequences of selected rules, multipliers and a
              random seed. Political figures are polling-calibrated illustrations,
              not measured local opinion or a prediction of a future referendum.
            </p>
          </section>
        </div>

        <section className="algorithm-section" aria-labelledby="algorithm-heading">
          <div className="algorithm-intro">
            <div className="brand-kicker">THE ALGORITHM</div>
            <h2 id="algorithm-heading">How one run evolves</h2>
            <p>
              A synthetic individual-level baseline, a YAML model and an explicit
              seed enter the same sequential loop for each year. The factual
              baseline year is shown unchanged before the loop advances.
            </p>
          </div>

          <figure className="pipeline-figure">
            <div className="pipeline-inputs" aria-label="Simulation inputs">
              <div><b>Synthetic baseline</b><span>Residents and attributes</span></div>
              <div><b>Model rules</b><span>Rates, controls and estimates</span></div>
              <div><b>Seed and adjustments</b><span>Reproducible scenario choices</span></div>
            </div>
            <div className="pipeline-arrow" aria-hidden="true">↓</div>
            <div className="pipeline-loop-label">Repeat for each projected year</div>
            <ol className="pipeline-steps">
              {PIPELINE_STEPS.map((step, index) => (
                <li key={step.title}>
                  <span className="pipeline-index" aria-hidden="true">
                    {String(index + 1).padStart(2, "0")}
                  </span>
                  <b>{step.title}</b>
                  <span>{step.detail}</span>
                </li>
              ))}
            </ol>
            <div className="pipeline-arrow" aria-hidden="true">↓</div>
            <div className="pipeline-output">
              <div>
                <b>Aggregate snapshot</b>
                <span>NI and LGD totals by age, community, sex and origin</span>
              </div>
              <span className="pipeline-output-arrow" aria-hidden="true">→</span>
              <div>
                <b>Polling calibration</b>
                <span>Estimated Unite, Remain and undecided views</span>
              </div>
              <span className="pipeline-output-arrow" aria-hidden="true">→</span>
              <div>
                <b>Browser display</b>
                <span>Aggregate statistics, map and playback only</span>
              </div>
            </div>
            <figcaption>
              Individual records evolve on the simulation engine. Only aggregates
              are streamed to the browser. The resulting population becomes the
              input to the next year.
            </figcaption>
          </figure>
        </section>

        <section className="about-footnote" aria-labelledby="use-heading">
          <h2 id="use-heading">Use it as a question generator</h2>
          <p>
            The useful questions are about sensitivity: which assumptions drive a
            result, whether a direction survives different seeds, and what evidence
            would be needed to replace an estimate. Do not use this project for
            policy, campaigning, investment, academic claims or factual forecasts.
          </p>
          <p>
            The repository is available under the permissive MIT License. You may
            use, copy, modify, merge, publish, distribute, sublicense and sell copies
            subject only to retaining its short copyright and permission notice.
          </p>
        </section>
      </article>
    </main>
  );
}
